version: incident/v1
id: 0576hsxrr4xx
name: Synthetic Monitoring Checks North Virginia Probe Down In prod-us-east-0
impact: minor
systems:
    - wlk38l1st21f
timeline:
    - ts: "2025-11-04 14:07:47"
      description: New checks for North Virginia can now be delivered. Some old checks may be affected too, but less likely.
    - ts: "2025-11-04 17:39:47"
      description: The incident is resolved as of 14:35 UTC.
      resolved: true
