version: incident/v1
id: 0p3rv4m4phjn
name: Hosted Grafana is currently being impacted as a result of the Cloudflare outage
impact: none
systems: []
timeline:
    - ts: "2025-12-05 09:25:44"
      description: We are currently experiencing disruptions to Hosted Grafana services due to a widespread Cloudflare outage impacting connectivity across multiple regions. Our team is actively monitoring the situation and will provide updates as Cloudflare works to restore normal operation.
      investigating: true
