version: incident/v1
id: 0wlcxfqv4dtb
name: Unable to Install Slack Integration
impact: major
systems:
    - z5ysrlvblv9t
timeline:
    - ts: "2026-02-11 14:21:58"
      description: We are aware of an issue that is preventing the installation of the Slack integration. We are currently investigating this, and will provide updates as they become available.
      investigating: true
    - ts: "2026-02-11 16:22:53"
      description: We have identified the issue, and are working on a fix.
    - ts: "2026-02-11 18:20:03"
      description: We are in the process of rolling out the fix.
    - ts: "2026-02-11 21:47:52"
      description: This incident has been resolved.
      resolved: true
