version: incident/v1
id: 2dwmwrsjf8lw
name: Synthetic monitoring secrets - proxy URL changes
impact: none
systems:
    - 3p25y2zfwhtc
    - nps7z0srxs25
    - yx5996c1lfnj
timeline:
    - ts: "2026-01-21 21:16:07"
      description: "During the secrets migration in https://status.grafana.com/incidents/47d1q4sphrmj,  secrets proxy URLs for some customers updated in the following regions: prod-us-central-0,  prod-us-east-0,  and prod-eu-west-2.  This was an unexpected breaking change affecting a subset of customers. \n\nThis will specifically affect customers who are using secrets on private probes behind a firewall. \n\nWe are investigating.  If your private probes are impacted,  we ask you to update firewall rules for the secrets proxy to allow outbound connections to the updated hosts: \n\ngsm-proxy-prod-eu-west-2.grafana.net -> gsm-proxy-prod-eu-west-4.grafana.net\ngsm-proxy-prod-us-central-0.grafana.net -> gsm-proxy-prod-us-central-4.grafana.net\ngsm-proxy-prod-us-east-0.grafana.net -> gsm-proxy-prod-us-east-2.grafana.net\n\nNote that this URL change affects only a small subset of customers, the majority of customers will not need to update firewall rules.  For affected customers, private probes will show the following error in probe logs, for example:\nError during test execution: failed to get secret: Get \"https://gsm-proxy-prod-us-east-2.grafana.net/api/v1/secrets/.../decrypt\": Forbidden undefined"
