version: incident/v1
id: 2nmspsj5w1ng
name: Metrics read issue affecting cortex-prod-13 on prod-us-east-0
impact: critical
systems:
    - 5270kl9kd6l2
timeline:
    - ts: "2025-12-10 08:23:00"
      description: |-
        At 08:04 UTC we detected read path outage (queries) on cortex-prod-13. We are currently investigating this issue.

        The ingestion path (writes) is not affected.
      investigating: true
