version: incident/v1
id: 39x1x9f0wzkh
name: IRM Pages Not Accessible
impact: critical
systems:
    - 1mxpk7q1bkb6
    - h3wg1km0qxwv
timeline:
    - ts: "2026-02-03 16:52:18"
      description: |-
        As of 16:40 UTC, we are currently investigating an issue where IRM pages are not accessible. Users may experience errors or be unable to load IRM-related pages during this time.

        Our team is actively working to identify the root cause and restore full functionality as quickly as possible. We will provide updates as more information becomes available.
      investigating: true
    - ts: "2026-02-03 17:29:05"
      description: The issue has been identified and we are implementing a fix.
    - ts: "2026-02-03 17:38:58"
      description: A fix as implemented, and we are seeing recovery throughout the rollout. We will continue to monitor results.
    - ts: "2026-02-03 17:56:40"
      description: This incident has been resolved.
      resolved: true
