version: incident/v1
id: 3lt64y9byrsy
name: 'Grafana Cloud: k6 -> Cloud Output Test Runs and Result Analysis (degraded performance).'
impact: none
systems: []
timeline:
    - ts: "2026-02-04 14:14:09"
      description: The HTTP Response time in the Performance trend overview did not show for new test-runs. After the fix, all data should show again.
      resolved: true
