version: incident/v1
id: 3phmw050wpwb
name: Investigating Issues with Email Delivery
impact: none
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - hl40gbs2zkn4
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - v2sp8gjnhwk6
    - lxb7122px698
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2026-01-23 15:37:50"
      description: We are currently investigating an issues impacting Email delivery for some Services, including Alert Notifications.
      investigating: true
    - ts: "2026-01-23 16:55:11"
      description: We are noticing significant improvement, and things are stabilizing as expected. Our engineering teams will continue to monitor progress.
    - ts: "2026-01-23 18:44:45"
      description: This incident has been resolved.
      resolved: true
