version: incident/v1
id: 4k54r5gzr7gr
name: Hyderabad Probe Issues
impact: minor
systems: []
timeline:
    - ts: "2025-11-17 19:01:44"
      description: We experienced degraded service with the Hyderabad probe today around 13:20 UTC which was resolved as of 17:30 UTC.
      resolved: true
