version: incident/v1
id: 61jzy6xxpv3m
name: Cortex - read/write path disruption
impact: major
systems:
    - dw1zzwblgd66
    - wg8xtz9dq3j4
timeline:
    - ts: "2025-11-17 14:06:33"
      description: We are currently observing a read/write path disruption in prod-us-central.cortex-prod-04.
    - ts: "2025-11-17 14:49:30"
      description: We are continuing to work on a fix for this issue.
