version: incident/v1
id: 6hz0rh05cpnw
name: Essential Maintenance for Faro Services
impact: none
systems:
    - fv8mjxqsls0c
    - 35qz76yfv9rv
    - gqmwwczllvq5
    - 0z4j4nzmq7hs
    - ytxxc3znw5jw
    - kzsv2pc2s30t
    - n90lmkqjvtcf
    - hkh69v8nwgz5
    - 72qxjs1p29q7
    - qf9z45tkj8s4
    - kklwl18sstbm
    - 00r5jb2jl7pt
    - 0s84b5yjppwy
    - cxvhcw6k5b06
    - csppcd2xw8l1
    - gz7h5z3g2fy0
    - 19pbz44xbzcg
    - 8wq67tm1cg31
    - 8klb6l621gd7
    - fn320fztp9hc
timeline:
    - ts: "2026-02-12 16:09:47"
      description: We are undergoing essential maintenance for Faro services. Users may experience a short outage for the service of <1 minute during this time. We expect this to be finished within an hour.
