version: incident/v1
id: 6s4k61gdjcft
name: Elevated Mimir Read/Write Errors
impact: major
systems:
    - 43jd9wwclvwy
    - 2lyhl59mn4dl
    - wlk38l1st21f
    - sn6tkms0qjs1
    - 5270kl9kd6l2
    - 9g6rbrbpph64
    - zqsjp5p0d8n7
    - 81f9yfcnyxsg
timeline:
    - ts: "2025-11-17 22:22:19"
      description: "We are investigating elevated Mimir read errors beginning at approximately 21:57 UTC. \n\nThe errors are technically retriable, but most retries are unlikely to succeed at this time. This may result in failed or delayed query responses for some users. \n\nEngineering is actively investigating the root cause and working to restore normal read performance. \n\nWe will provide further updates as we learn more."
      investigating: true
    - ts: "2025-11-17 22:33:24"
      description: Span metrics have also been identified as affected. We are continuing to investigate the root cause and will share further updates as more information becomes available.
      investigating: true
    - ts: "2025-11-17 22:47:12"
      description: The investigation has revealed that metric ingestion is also affected, including log-generated recording rules. We are continuing to investigate the root cause and will provide further updates as more information becomes available.
      investigating: true
    - ts: "2025-11-17 22:47:58"
      description: The investigation has revealed that metric ingestion is also affected, including log-generated recording rules. We are continuing to investigate the root cause and will provide further updates as more information becomes available.
      investigating: true
    - ts: "2025-11-17 22:55:29"
      description: "Our teams have been alerted that Synthetic Monitoring will also be affected by this outage. \n\nUsers may see gaps in their Synthetic Monitoring metrics as well as missed alerts as a result of this. \n\nWe continue to investigate and will provide further updates as they become available."
      investigating: true
