version: incident/v1
id: 7kcpmzc6ws9v
name: Mimir Partial Write Outage
impact: major
systems:
    - mhjps7348n0g
    - 82s7r3tjyb6n
    - dcwlkh9jb6xh
timeline:
    - ts: "2025-12-11 21:43:17"
      description: "As of 21:30 UTC, we are experiencing a partial ingestion outage in Grafana Mimir. This is affecting the write path, where some ingestion requests are failing or timing out. \n\nOur engineering team is actively investigating and working to identify the root cause."
      investigating: true
    - ts: "2025-12-11 22:23:16"
      description: While investigating this issue, we also became aware that Synthetic Monitoring is affected. Some customers may have alert rules failing to evaluate.
      investigating: true
    - ts: "2025-12-11 22:33:24"
      description: Engineering has released a fix and as of 22:25 UTC, customers should no longer experience ingestion issues. We will continue to monitor for recurrence and provide updates accordingly.
    - ts: "2025-12-11 23:02:53"
      description: "Synthetic Monitoring has now also recovered. Customers should no longer experience alert rules failing to evaluate. \n\nWe continue to monitor for recurrence and will provide updates accordingly."
    - ts: "2025-12-11 23:17:04"
      description: We continue to observe a continued period of recovery. At this time, we are considering this issue resolved. No further updates.
      resolved: true
