version: incident/v1
id: 7lqrxkt8hb8v
name: Partial Write Outage in prod-us-central-0
impact: none
systems: []
timeline:
    - ts: "2026-01-07 17:41:16"
      description: There was a ~15 minute partial write outage for some customers in prod-us-central-0. The time frame for this outage was 15:43-15:57 UTC.
      resolved: true
