version: incident/v1
id: 9qxj7s6jsgqm
name: Tempo write degradation in prod-eu-west-3 - tempo-prod-08
impact: minor
systems:
    - zq01gnnnsqsd
    - cm40jcy1klhh
    - gcwgxxhzztdh
timeline:
    - ts: "2026-01-12 09:03:43"
      description: We have been alerted to an issue with Tempo write degradation in prod-eu-west-3 - tempo-prod-08. The cell is operational but there is degradation in the write path. Write requests are taking longer than normal. This started at started 7:00 UTC. Our Engineering team is actively investigating this.
      investigating: true
    - ts: "2026-01-12 09:09:58"
      description: We are continuing to investigate this issue.
      investigating: true
    - ts: "2026-01-12 11:41:43"
      description: There was a full degradation of write service between 9:13 UTC - 9:35 UTC. The cell is operational but there is still degradation in the write path. Our Engineering team is actively working on this.
      investigating: true
    - ts: "2026-01-12 15:26:03"
      description: Engineering has released a fix and we continue to observe a period of recovery. As of 15:12 UTC we are considering this resolved.
      resolved: true
