version: incident/v1
id: d3qybpc3yt3f
name: Degraded dashboard performance due to the erroneous security policy
impact: minor
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2024-11-15 12:21:35"
      description: We have introduced an erroneous security policy (CSP) that can break user dashboards. We are rolling back the update now.
    - ts: "2024-11-15 17:23:02"
      description: Rollback has been completed as of 17:20 UTC. At this time, we are considering this issue resolved. No further updates.
      resolved: true
