version: incident/v1
id: dq9vhj7z439f
name: Loki Prod 012 read-path-unstable
impact: minor
systems:
    - gx6m1v8jy475
timeline:
    - ts: "2025-11-17 04:12:52"
      description: A fix has been implemented and we are monitoring the results.
