version: incident/v1
id: dq9vhj7z439f
name: Loki Prod 012 read-path-unstable
impact: minor
systems:
    - gx6m1v8jy475
timeline:
    - ts: "2025-11-17 04:12:52"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2025-11-17 04:13:48"
      description: We started having instabilities for recording rules of this cell starting at 2:30 AM UTC. They started recovering at around 3 AM UTC, but we're still watching.
    - ts: "2025-11-17 04:55:49"
      description: resolved since 03:02UTC
      resolved: true
