version: incident/v1
id: gphjhq510r1v
name: Degraded Writes in AWS us-east-2
impact: none
systems: []
timeline:
    - ts: "2026-01-17 11:28:13"
      description: We are currently investigating an issue causing degraded write performance across multiple products in the AWS us-east-2 region. Our engineering team is actively working to determine the full scope and impact of the issue and restore normal service levels.
      investigating: true
