version: incident/v1
id: gyys60pphphf
name: Athena Queries Broken
impact: minor
systems: []
timeline:
    - ts: "2026-02-09 15:35:06"
      description: We are currently investigating an issue resulting in broken queries for the Athena data source.
      investigating: true
    - ts: "2026-02-09 16:23:44"
      description: Our engineering team is still investigating this issue.
      investigating: true
    - ts: "2026-02-09 17:01:16"
      description: We are seeing recovery in impacted environments. We will continue to monitor the progress.
