version: incident/v1
id: h728vzp1xdrs
name: Incorrect pipeline assignment after custom attributes are assigned
impact: minor
systems:
    - 3jbh6nyxv692
timeline:
    - ts: "2026-02-27 12:57:47"
      description: We are investigating issues with incorrect pipeline assignment after custom attributes are assigned.
      investigating: true
    - ts: "2026-02-27 13:39:57"
      description: The issue has been identified and we are working on a fix.
    - ts: "2026-02-27 15:24:39"
      description: This incident has been resolved.
      resolved: true
