version: incident/v1
id: h85d5cxfq3nl
name: Grafana Cloud Metrics - Intermittent Write Latency in prod-us-central and prod-us-central-5.
impact: minor
systems:
    - 1tt4gx4t4q87
    - l778xg16mls4
timeline:
    - ts: "2026-02-25 19:54:15"
      description: Since February 19, we have been investigating an intermittent issue causing increased write latency in the prod-us-central-0 and prod-us-central-5 regions. The issue does not affect all traffic but may result in delayed write operations for some customers. Our engineering team is actively working to identify the root cause and stabilize performance. We will share additional updates as progress is made.
      investigating: true
    - ts: "2026-02-26 16:23:32"
      description: We have begun rolling out mitigation steps to reduce write latency in the prod-us-central-0 and prod-us-central-5 regions. While these measures are expected to improve performance, we are continuing to investigate the underlying root cause of the issue. We will provide additional updates as more information becomes available.
      investigating: true
