version: incident/v1
id: hl8s6d9sllcj
name: Upgrade from Free â†’ Pro failing for users
impact: major
systems:
    - 0s4n2mv9hwv9
timeline:
    - ts: "2026-01-26 20:53:56"
      description: |-
        As of 20:05 UTC, our engineering team became aware of an issue related to subscription plan upgrades. Users experiencing this issue will not be able to upgrade from a Free plan to a Pro subscription.

        Engineering is actively engaged and assessing the issue. We will provide updates accordingly.
      investigating: true
    - ts: "2026-01-26 21:52:01"
      description: |-
        Engineering has identified the issue and is currently exploring remediation options. At this time, users will continue to experience the inability to upgrade from Free to Pro subscriptions.

        We will continue to provide updates as more information is shared.
    - ts: "2026-01-27 00:13:54"
      description: Engineering has released a fix and as of 00:13 UTC, customers should no longer experience issues upgrading from Free to Pro subscriptions. At this time, we are considering this issue resolved. No further updates.
      resolved: true
