version: incident/v1
id: hsv85lv8dc6g
name: Increased write error rate for logs in prod-us-west-0
impact: none
systems:
    - 6rlxmdg0t6v3
timeline:
    - ts: "2026-01-27 07:49:39"
      description: We were experiencing increased write error rate for logs in prod-us-west-0 from 6:55 to 7:15 UTC. We have since observed continued stability and are marking this as resolved.
      resolved: true
