version: incident/v1
id: jhbp1q8xdxkx
name: K6 test-runs cannot be started and the overall navigation experience is degraded
impact: minor
systems:
    - 3gvy1n7fg4x4
    - m79yjv169r06
timeline:
    - ts: "2026-01-02 10:44:19"
      description: We are currently investigating this issue.
      investigating: true
    - ts: "2026-01-02 11:51:49"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2026-01-02 11:53:03"
      description: We are continuing to monitor for any further issues.
    - ts: "2026-01-02 13:38:35"
      description: This incident has been resolved.
      resolved: true
