version: incident/v1
id: kzlbmh20s6sx
name: Inconsistent threshold check results reported intermittently
impact: minor
systems:
    - z9074fpyx6sb
timeline:
    - ts: "2026-02-04 17:20:49"
      description: |-
        We encountered a subtle bug which caused our test-run finalization process to read from stale threshold status because of a synchronization issue.

        We have since resolved the bug, and new test runs will work properly. Impacted test runs will need to be fixed via further correction on our end. We will continue to provide updates on the progress of the fix for impacted test runs.
    - ts: "2026-02-04 19:57:23"
      description: We are continuing to work on a fix for this issue.
    - ts: "2026-02-05 09:36:23"
      description: The issue causing the incident has been identified, and the fix has been deployed. All new test runs work consistently
    - ts: "2026-02-05 15:31:33"
      description: This incident has been resolved.
      resolved: true
