version: incident/v1
id: kzlbmh20s6sx
name: Inconsistent threshold check results reported intermittently
impact: minor
systems:
    - wbhrnd130mb0
timeline:
    - ts: "2026-02-04 17:20:49"
      description: |-
        We encountered a subtle bug which caused our test-run finalization process to read from stale threshold status because of a synchronization issue.

        We have since resolved the bug, and new test runs will work properly. Impacted test runs will need to be fixed via further correction on our end. We will continue to provide updates on the progress of the fix for impacted test runs.
