version: incident/v1
id: mgss96trzn1l
name: Elevated Metric Push Failures and Latency
impact: major
systems:
    - d2vdtkjjdzjy
    - wy292mxvxhxv
timeline:
    - ts: "2025-12-10 19:29:12"
      description: |-
        We have detected an issue causing some customers to experience failed metric pushes as well as increased latency when sending metrics. The issue was first observed at 18:30 UTC.

        Our engineering team is actively investigating the root cause and working to restore normal operation as quickly as possible. We will provide further updates as more information becomes available.

        Thank you for your patience while we work to resolve this issue.
      investigating: true
    - ts: "2025-12-10 19:49:17"
      description: We have also identified that trace ingestion may also be affected. Some customers may experience elevated latency and intermittent errors when sending traces. Investigation is ongoing.
      investigating: true
    - ts: "2025-12-10 19:49:48"
      description: We are continuing to investigate this issue.
      investigating: true
    - ts: "2025-12-10 20:48:15"
      description: Our engineering team has engaged with our Cloud Service Provider and are working together to continue to investigate this issue.
      investigating: true
    - ts: "2025-12-10 21:38:23"
      description: Our engineering team has identified a potential root cause, and a fix is being implemented.
    - ts: "2025-12-10 22:22:56"
      description: "We are observing a trend in improvement after implementing a fix. We will continue to monitor and update accordingly. \n\nDuring our investigation, we also became aware that some alerts associated with Synthetic Monitoring checks have been failing to evaluate correctly."
    - ts: "2025-12-10 23:05:38"
      description: We continue to observe a continued period of recovery. At this time, we are considering this issue resolved. No further updates.
      resolved: true
