version: incident/v1
id: n6jhwt7bkrw6
name: Slow user queries exceeds threshold
impact: minor
systems:
    - 2lyhl59mn4dl
timeline:
    - ts: "2025-11-21 12:09:11"
      description: We are currently investigating this issue.
      investigating: true
    - ts: "2025-11-21 12:10:56"
      description: We are having some intermittent query failures
      investigating: true
    - ts: "2025-11-21 13:08:18"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2025-11-21 14:52:08"
      description: This incident has been resolved.
      resolved: true
