version: incident/v1
id: qhd431syk6df
name: Hosted grafana is currently being impacted as a result of the Cloudflare outage
impact: none
systems: []
timeline:
    - ts: "2025-11-18 11:59:18"
      description: We are currently experiencing disruption to Hosted Grafana services due to a widespread Cloudflare outage impacting connectivity across multiple regions. Our team is actively monitoring the situation and will provide updates as Cloudflare works to restore normal operation.
      investigating: true
