version: incident/v1
id: qls5gfcfsbxm
name: Metrics Write Outage in Multiple Cells
impact: major
systems:
    - 1tt4gx4t4q87
    - 7p6gpdprypb9
    - l778xg16mls4
timeline:
    - ts: "2025-11-17 20:02:42"
      description: "We are investigating a partial write outage affecting multiple metrics cells, beginning around 19:30 UTC. Some customers may see intermittent write failures or delays, but most requests should succeed after retries and recent metrics may appear late as a result. \n\nQuerying previously ingested data remains unaffected. Engineering is continuing to investigate and will provide further updates as more information becomes available."
      investigating: true
    - ts: "2025-11-17 20:11:19"
      description: "Mitigation has been applied and Mimir write performance is beginning to recover in the affected cells. \n\nprod-us-central-0.cortex-prod-10 appears to have recovered as of 19:52 UTC, and prod-us-central-5.cortex-dedicated-06 is showing signs of recovery as of 20:00 UTC. \n\nWe are continuing to monitor both cells closely to ensure the mitigation is effective and that the systems remain stable."
    - ts: "2025-11-17 20:34:33"
      description: "We’ve re-evaluated the situation and this issue is still ongoing. Although we initially observed signs of recovery, write errors continue to occur in the affected cells. \n\nMitigation work is still in progress, and we’re treating the incident as identified again while we work toward a sustained resolution. We’ll provide further updates as we confirm stabilization."
    - ts: "2025-11-17 20:50:24"
      description: "Our teams have been alerted that Synthetic Monitoring will also be affected by this outage. \n\nUsers may see gaps in their Synthetic Monitoring metrics as well as missed alerts as a result of this. \n\nWe continue to investigate and will provide further updates as they become available."
    - ts: "2025-11-17 21:22:57"
      description: "We are seeing improvement on the metrics side, with write performance recovering. \n\nWe continue to investigate the remaining impact to Synthetic Monitoring and are working to determine the underlying cause. \n\nMonitoring will continue as recovery progresses, and we’ll provide further updates as we learn more."
    - ts: "2025-11-17 23:08:40"
      description: "As of 23:07 UTC we are considering this incident as resolved. \n\nMitigation efforts have restored normal write performance, and error rates have returned to expected levels. \n\nWe have confirmed stability across the affected areas and continue to monitor, but no further impact is expected. \n\nIf you continue to experience any issues, please reach out to support."
      resolved: true
