version: incident/v1
id: rd9mtdkhnsbw
name: Degraded performance of Grafana Cloud k6 test runs
impact: minor
systems:
    - m79yjv169r06
timeline:
    - ts: "2026-02-18 08:27:56"
      description: We see intermittent failures and slow start-up of test-runs. We are currently investigating this issue.
      investigating: true
    - ts: "2026-02-18 10:20:45"
      description: We are continuing to investigate this issue.
      investigating: true
    - ts: "2026-02-18 12:57:55"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2026-02-18 21:17:12"
      description: This incident has been resolved.
      resolved: true
