version: incident/v1
id: szsvlbg4md4k
name: PDC Queries in Prod-Us-East-3 Are Failing
impact: minor
systems: []
timeline:
    - ts: "2025-12-23 20:31:35"
      description: We are currently investigating an issue impacting PDC Queries in the Prod-Us-East-3 region. This issue is causing queries to fail, and affected customers are experiencing "no such host" errors when attempting to connect a data source via PDC.
      investigating: true
    - ts: "2025-12-23 20:34:13"
      description: We have identified the issue, and are working on a fix now.
    - ts: "2025-12-23 21:09:26"
      description: A fix has been implemented and we are monitoring the results.
