version: incident/v1
id: xmjhgqz380qn
name: No services are reachable in prod-us-central-7
impact: major
systems:
    - 2gj2jt684k11
    - gxyxxd4nr755
    - l1hs6x2ml5hn
    - xjv0q11xqq2b
timeline:
    - ts: "2025-11-03 12:36:34"
      description: |-
        We became aware of an issue with the services in prod-us-central-7. Users experiencing this issue may encounter  issues sending data to Grafana Cloud.


        We are working on recovery.
      investigating: true
    - ts: "2025-11-03 12:58:26"
      description: "A fix has been implemented and we can see the system are recovering everywhere. \nWe're monitoring the situation."
    - ts: "2025-11-03 14:13:53"
      description: This incident has been resolved.
      resolved: true
