version: incident/v1
id: yb1s66066xmq
name: Alerts failing with prometheus
impact: minor
systems:
    - jhc34sjt42wd
timeline:
    - ts: "2025-11-27 16:49:37"
      description: We are currently investigating an issue around degraded services in prod-us-central-0. The expected behavioral impact is that the queries may take longer than usual to respond.
      investigating: true
    - ts: "2025-11-27 18:02:31"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2025-11-27 18:27:57"
      description: This incident has been resolved.
      resolved: true
