version: incident/v1
id: zcyvll30yxd7
name: Self-Serve Users Unable to Sign Up
impact: major
systems:
    - m0qkgdzwyr6l
timeline:
    - ts: "2026-02-13 18:40:03"
      description: We are currently investigating an issue which is causing users the inability to sign up for self-serve Grafana. We will continue to update with more information as we progress our investigation.
      investigating: true
