version: incident/v1
id: zdnjtgxrv2rg
name: Multiple free tier customers are getting "no fields to display" when viewing logs instead of labels and structured metadata
impact: minor
systems:
    - bg6nnf5n3pjx
    - 1cj80yl7f6dy
    - 9z18xdj3j8c7
    - gx6m1v8jy475
    - ttlshz10ly19
    - 318npch70m7f
    - nfll10wmx61f
    - dy7xwydh5kv3
    - k21kfy4lhmdw
    - 2lyhl59mn4dl
    - 6rlxmdg0t6v3
    - hqf81r9207h6
    - tpk4cdhtsm82
    - 2gj2jt684k11
    - d6hp5brmvsbt
    - rwvs9fvrnhp2
    - x40g7bxm0q2d
    - v3g3j6krw8rp
    - gp2m13gyj6x2
    - 662yyglvgqpm
    - l72f5c7651n5
    - 98skfgrdgchf
timeline:
    - ts: "2026-02-06 11:29:49"
      description: We are currently investigating this issue.
      investigating: true
