version: incident/v1
id: zw37sgb2l4lx
name: Longer Than Expected Load Times on Grafana Cloud
impact: major
systems: []
timeline:
    - ts: "2025-11-21 15:47:30"
      description: We are currently investigating reports of long load times on Grafana Cloud. We will update as more information becomes available.
      investigating: true
